name: Publish

on:
  push:
    branches: [ "main" ]

jobs:

  microtests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebug

  instrumented:
    name: Run instrumented tests
    runs-on: macos-latest

    steps:
      uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          script: ./gradlew connectedCheck

  distribute:
    name: Distribute app bundle to Play Store
    needs: [ microtests, instrumented ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Version bump
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Assemble app bundle
        run: ./gradlew bundleRelease

      - name: Sign app bundle for release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.FRIENDS_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.FRIENDS_KEY_PASSWORD }}

      - name: Setup authorization with Google Play Store
        run: echo '${{ secrets.GOOGLE_PLAY_KEY }}' > service_account.json

      - name: Deploy to internal
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJson: service_account.json
          packageName: com.github.mohaka.friends
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: 'completed'
          whatsNewDirectory: whatsNewDirectory/